version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "main"
  ignore:
    - dependency-name: "symfony/console"
      versions: [ "6.x" ]
    - dependency-name: "symfony/event-dispatcher"
      versions: [ "6.x" ]
    - dependency-name: "symfony/http-foundation"
      versions: [ "6.x" ]
    - dependency-name: "symfony/mailer"
      versions: [ "6.x" ]
    - dependency-name: "symfony/process"
      versions: [ "6.x" ]
    - dependency-name: "symfony/routing"
      versions: [ "6.x" ]
    - dependency-name: "symfony/translation"
      versions: [ "6.x" ]

- package-ecosystem: composer
  directory: "/"
  target-branch: stable27
  schedule:
    interval: weekly
    day: saturday
    time: "03:10"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  labels:
    - "dependencies"
    - "stable27"


- package-ecosystem: composer
  directory: "/"
  target-branch: stable26
  schedule:
    interval: weekly
    day: saturday
    time: "03:20"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  labels:
    - "dependencies"
    - "stable26"

- package-ecosystem: composer
  directory: "/"
  target-branch: stable25
  schedule:
    interval: weekly
    day: saturday
    time: "03:30"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  labels:
    - "dependencies"
    - "stable25"
